#!/bin/sh
xrandr \
 --output LVDS --off \
 --output DFP10 --off \
 --output DFP11 --off \
 --output DFP12 --off \
 --output CRT1 --mode 1920x1200 --pos 0x0 --rotate normal \
 --output DFP8 --off \
 --output DFP9 --off \
 --output DFP6 --off \
 --output DFP7 --off \
 --output DFP4 --off \
 --output DFP5 --off \
 --output DFP2 --off \
 --output DFP3 --off \
 --output DFP1 --off
